version: '3.8'

services:
  postgres:
    container_name: to-do-task
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=vinicius
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=to-do-task
      - PGDATA=/data/postgres
    volumes:
      - ./data/pg:/data/postgres